# These are supported funding model platforms

github: [victorvhn] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: victorvhn # Replace with a single Patreon username
